-- Run once in the Supabase SQL editor. Brings a database created from an older setup.sql in line
-- with what the app expects (lib/schema.ts). Safe to re-run.

-- "Endangered" flag used by the add/edit species dialogs
alter table species
  add column if not exists endangered boolean not null default false;

-- Comments shown in the species "Learn more" dialog
create table if not exists comments (
  id int generated by default as identity primary key,
  species_id int not null references species on delete cascade,
  author uuid not null references profiles,
  content text not null,
  created_at timestamptz not null default now()
);
alter table comments
  enable row level security;

drop policy if exists "Comments are viewable by everyone." on comments;
create policy "Comments are viewable by everyone." on comments
  for select using (true);

drop policy if exists "Users can insert their own comments." on comments;
create policy "Users can insert their own comments." on comments
  for insert with check (auth.uid() = author);

drop policy if exists "Users can delete their own comments." on comments;
create policy "Users can delete their own comments." on comments
  for delete using (auth.uid() = author);

-- Make PostgREST pick up the new column/table immediately
notify pgrst, 'reload schema';
