-- Run this in the Supabase SQL editor AFTER you have run the webapp and logged in at least once. You need to make sure the `profiles` table has at least one user in it.
-- This will populate the database with some seed data you can use, with the author for each species set to the first user in the `profiles` table.

do $$
declare
  user_id uuid;
begin
  select id from profiles limit 1 into user_id;

  insert into
  species(scientific_name,	common_name,	total_population,	kingdom,	description,	author,	image)
  values
    ('Cavia porcellus',	'Guinea Pig',	1000,	'Animalia',	'The guinea pig or domestic guinea pig (Cavia porcellus), also known as the cavy or domestic cavy (/Ààke…™vi/ KAY-vee), is a species of rodent belonging to the genus Cavia in the family Caviidae', user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/Guinea_pig_2011_01_10_12_58_15.jpg/500px-Guinea_pig_2011_01_10_12_58_15.jpg'),
    ('Opuntia ficus-indica',	'Prickly Pear',	null,	'Plantae',	'Opuntia ficus-indica, the Indian fig opuntia, fig opuntia, or prickly pear, is a species of cactus that has long been a domesticated crop plant grown in agricultural economies throughout arid and semiarid parts of the world.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Dikenli_%C4%B0ncir_%28Opuntia_ficus-indica%29_Gaziantep_Turkey.IMG_1104.jpg/500px-Dikenli_%C4%B0ncir_%28Opuntia_ficus-indica%29_Gaziantep_Turkey.IMG_1104.jpg'),
    ('Odontodactylus scyllarus',	'Mantis Shrimp',	5000,	'Animalia',	'Called "sea locusts" by ancient Assyrians, "prawn killers" in Australia, and now sometimes referred to as "thumb splitters" because of the animal''s ability to inflict painful wounds if handled incautiously, mantis shrimp have powerful raptorial appendages that are used to attack and kill prey either by spearing, stunning, or dismembering.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/Odontodactylus_scyllarus_R%C3%A9union.jpg/500px-Odontodactylus_scyllarus_R%C3%A9union.jpg'),
    ('Glaucus atlanticus',	'Blue Sea Dragon',	null,	'Animalia',	'Glaucus atlanticus is a species of small, blue sea slug, a pelagic (open-ocean) aeolid nudibranch, a shell-less gastropod mollusk in the family Glaucidae.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/21/Glaucus_atlanticus_1_cropped.jpg/500px-Glaucus_atlanticus_1_cropped.jpg'),
    ('Leuresthes tenuis',	'California grunion',	null,	'Animalia',	'Leuresthes tenuis, the California grunion, is a species of ray-finned fish native to the Pacific coast of North America from Monterey Bay in California to Baja California',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Leuresthes_tenuis.jpg/500px-Leuresthes_tenuis.jpg'),
    ('Cyanocitta stelleri',	'Steller''s jay',	null,	'Animalia',	'Steller''s jay (Cyanocitta stelleri) is a bird native to western North America and the mountains of Central America, closely related to the blue jay found in eastern North America',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Steller%27s_Jay_flagstaff_arizona.jpg/500px-Steller%27s_Jay_flagstaff_arizona.jpg'),
    ('Grimpoteuthis',	'Dumbo Octopus',	null,	'Animalia',	'Grimpoteuthis is a genus of pelagic finned or cirrate octopods known as the dumbo octopuses. The name "dumbo" originates from their resemblance to the title character of Disney''s 1941 film Dumbo, having a prominent ear-like fin which extends from the mantle above each eye. ',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Grimpoteuthis_2108m.jpg/500px-Grimpoteuthis_2108m.jpg'),
    ('Homo Sapiens',	'Humans',	700000000,	'Animalia',	'Humans (Homo sapiens) are the most common and widespread species of primate. A great ape characterized by their bipedalism and high intelligence, humans have a large brain and resulting cognitive skills that enable them to thrive in varied environments and develop complex societies and civilizations',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/A_Man_on_the_Moon%2C_AS11-40-5903_%28cropped%29.jpg/500px-A_Man_on_the_Moon%2C_AS11-40-5903_%28cropped%29.jpg'),
    ('Ursus maritimus',	'Polar Bear',	null,	'Animalia',	'The polar bear (Ursus maritimus) is a hypercarnivorous species of bear. Its native range lies largely within the Arctic Circle, encompassing the Arctic Ocean and its surrounding seas and landmasses, which includes the northernmost regions of North America and Eurasia. It is the largest extant bear species, as well as the largest extant land carnivore.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/Polar_Bear_ANWR_10.jpg/500px-Polar_Bear_ANWR_10.jpg'),
    ('Panthera uncia',	'Snow leopard',	10000,	'Animalia',	'The snow leopard (Panthera uncia), commonly known as the ounce, is a species of large cat in the genus Panthera of the family Felidae. The species is native to the mountain ranges of Central and South Asia. It is listed as Vulnerable on the IUCN Red List because the global population is estimated to number fewer than 10,000 mature individuals and is expected to decline about 10% by 2040.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Lightmatter_snowleopard.jpg/500px-Lightmatter_snowleopard.jpg'),
    ('Panthera leo',	'Lion',	10000,	'Animalia',	'The lion (Panthera leo) is a large cat of the genus Panthera native to Africa and India. It has a muscular, broad-chested body; short, rounded head; round ears; and a hairy tuft at the end of its tail. It is sexually dimorphic; adult male lions are larger than females and have a prominent mane.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/500px-020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg'),
    ('Ailuropoda melanoleuca',	'Giant Pandas',	3000,	'Animalia',	'The giant panda (Ailuropoda melanoleuca, sometimes panda bear or simply panda) is a bear species endemic to China. It is characterised by its bold black-and-white coat and rotund body. The name "giant panda" is sometimes used to distinguish it from the red panda, a neighboring musteloid. Though it belongs to the order Carnivora, the giant panda is a folivore, with bamboo shoots and leaves making up more than 99% of its diet',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/500px-Grosser_Panda.JPG'),
    ('Panthera ',	'Tiger',	2000,	'Animalia',	'The tiger (Panthera tigris) is the largest living cat species and a member of the genus Panthera.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg/500px-Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg'),
    ('Psychrolutes marcidus',	'Blobfish',	50,	'Animalia',	'The fish family Psychrolutidae (commonly known as blobfishes, toadfishes, flathead sculpins, tadpole sculpins) contains over 35 recognized species in 8 genera. This family consists of bottom-dwelling marine sculpins shaped like tadpoles, with large heads and bodies that taper back into small, flat tails.',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Psychrolutes_marcidus.jpg/500px-Psychrolutes_marcidus.jpg'),
    ('Giraffa',	'Giraffe',	3000,	'Animalia',	'The giraffe is a large African hoofed mammal belonging to the genus Giraffa. It is the tallest living terrestrial animal and the largest ruminant on Earth. Traditionally, giraffes were thought to be one species, Giraffa camelopardalis, with nine subspecies',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/500px-Giraffe_Mikumi_National_Park.jpg'),
    ('Folivora',	'Sloth',	1500,	'Animalia',	'Sloths are a Neotropical group of xenarthran mammals constituting the suborder Folivora, including the extant arboreal tree sloths and extinct terrestrial ground sloths. Noted for their slowness of movement, tree sloths spend most of their lives hanging upside down in the trees of the tropical rainforests of South America and Central America',	user_id,	'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Bicho-pregui%C3%A7a_3.jpg/500px-Bicho-pregui%C3%A7a_3.jpg');

end; $$;
